# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.14.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/arbitraryrw/MobProtID
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: echo "Starting building now.."
      - run: echo "Working dir:" `pwd` 
      - run: sudo apt-get install android-sdk
      - run: sudo apt-get install automake libtool make gcc
      - run: wget https://github.com/VirusTotal/yara/archive/v3.11.0.tar.gz
      - run: tar -zxf v3.11.0.tar.gz
      - run: cd yara-3.11.0/ && ./bootstrap.sh
      - run: cd yara-3.11.0/ && ./configure
      - run: cd yara-3.11.0/ && make
      - run: cd yara-3.11.0/ && sudo make install
      - run: cd yara-3.11.0/ && make check
      - run: sudo apt-get install libyara-dev
      - run: wget https://github.com/radareorg/radare2/archive/4.4.0.zip
      - run: sudo apt-get install patch
      - run: unzip 4.4.0.zip
      - run: cd radare2-4.4.0/ && sys/user.sh
      - run: go get -v -t -d ./...
      - run: go test -v ./...